### ISSUE TITLE
Getting HMAC error when inserting UTF-8 character "Ö" in Atom

### ISSUE THREAD

**Issue by fl0w** [zxqfl/tabnine-atom#1]
Hi,

I've encountered this by mistake a few times as I switch between sv_SE and en_US keyboard layout.
Whenever I insert any Swedish character (by accident) I get.

```sh
Error: Bad Hmac
    at IncomingMessage.<anonymous> (/Users/fl0w/.atom/packages/TabNine/lib/handler.coffee:159:20)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

The plugin continues to work as expected if atom notification is ignored.

**Comment by csvoss** [comment]
I get the same issue when I accidentally hit my § key*, in case that's useful for narrowing this issue down.

*My Kinesis Advantage2 keyboard has a key that produces this character. It's not actually a key that I use for anything, so this issue is not blocking me.

**Comment by desmondw** [comment]
This happens for most uncommon characters, including ‘quotes’ and ”double quotes”. Quite annoying.
