### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by olligobber** [zxqfl/tabnine-atom#7]
When I try to install in Atom 1.34.0 on Arch Linux I get `Installing "TabNine@0.1.5" failed` with the output

```
internal/modules/cjs/loader.js:718
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /usr/lib/node_modules/atom-package-manager/node_modules/git-utils/build/Release/git.node: undefined symbol: _ZN2v811HandleScope12CreateHandleEPNS_8internal24NeverReadOnlySpaceObjectEPNS1_6ObjectE
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:371:4)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

**Comment by olligobber** [comment]
Ok, this is now happening even when not installing TabNine, so I believe it is unrelated.

**Comment by olligobber** [comment]
Posted to a more appropriate location: https://github.com/atom/apm/issues/828
